services:
  postgres:
    image: postgres:14.20-trixie
    container_name: ticket_booking_db
    environment:
      POSTGRES_DB: ticket_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticket_booking_network

  redis:
    image: redis
    container_name: ticket_booking_redis
    ports:
      - "6379:6379"
    networks:
      - ticket_booking_network

volumes:
  postgres_data:

networks:
  ticket_booking_network:
