services:
  postgres:
    image: mysql:8
    container_name: ticket_booking_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_booking
      MYSQL_USER: ticketuser
      MYSQL_PASSWORD: ticketpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ticket_booking_network

  redis:
    image: redis
    container_name: ticket_booking_redis
    ports:
      - "6379:6379"
    networks:
      - ticket_booking_network

volumes:
  mysql_data:

networks:
  ticket_booking_network:
